const User = require("./user.js");
const Film = require("./film.js");

var films = new Array();
var films_aux = new Array("Action","War");
var genres = new Array();
var actors = new Array();
var usuario = new User(films,genres);
var film = new Film("Hamsel y gretel",2020,"oe",films_aux,actors);
usuario.addGenre("Comedy");
//usuario.addGenre("jeje");
console.log("Hola mundo");
console.log(usuario.genres);
usuario.delGenre("Comedy");
console.log(usuario.genres);
usuario.setGenres(films_aux);
console.log(usuario.genres);
usuario.addFilm(film);
console.log(usuario.films);
console.log(film);
film.setTitle("jej ");
console.log(film);
film.addGenre("Thriller");
console.log("Cambio hecho");
console.log(film);
film.addActor("Leonardo Di Caprio");
console.log(film);
film.delActor("Leonardo Di Caprio");
console.log(film);