name: Refresh DockerHub GitHub Action

# Se ejecutará cada vez que se modifiquen estos archivos
on:
  push:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "Dockerfile"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    steps:
      # Inicia sesión en DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Actualiza la imagen subida
      - name: Refresh image
        uses: docker/build-push-action@v3
        with:
          content: .
          push: true
          tags: "pablo1mc315/iv_pablomc:latest"
      

